# Generated by Django 5.2.5 on 2025-11-13 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bg_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('font_type', models.CharField(default='Arial', max_length=20)),
                ('bg_music', models.CharField(blank=True, max_length=100, null=True)),
                ('joke_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
