# Generated by Django 5.2.5 on 2025-11-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
