# Generated by Django 5.2.5 on 2025-11-14 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_joke_font_type_jokecomment_jokelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_jokes', to=settings.AUTH_USER_MODEL),
        ),
    ]
