# Generated by Django 5.2.5 on 2025-11-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_joke_likers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jokecomment',
            unique_together=set(),
        ),
    ]
