# Generated by Django 5.2.5 on 2025-11-16 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_jokemusic_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='bg_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.jokemusic'),
        ),
    ]
