# Generated by Django 5.2.5 on 2026-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_joke_bg_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokemusic',
            name='file_url',
            field=models.FileField(max_length=255, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='jokemusic',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
